export interface Destination {
  id: string
  name: string
  country: string
  continent: string
  description: string
  highlights: string[]
  bestTime: string
  avgTemp: string
  currency: string
  language: string
  timezone: string
  flightTime: string
  avgFlightPrice: number
  rating: number
  reviews: number
  tags: string[]
  images: string[]
}

export const destinations: Destination[] = [
  {
    id: 'paris',
    name: 'Paris',
    country: 'Francia',
    continent: 'Europa',
    description: 'La Ciudad de la Luz, famosa por su arte, arquitectura y gastronomia. Hogar de la Torre Eiffel, el Louvre y los Campos Eliseos.',
    highlights: ['Torre Eiffel', 'Museo del Louvre', 'Campos Eliseos', 'Notre-Dame', 'Montmartre', 'Palacio de Versalles'],
    bestTime: 'Abril - Octubre',
    avgTemp: '12°C',
    currency: 'EUR',
    language: 'Frances',
    timezone: 'UTC+1',
    flightTime: '2h desde Madrid',
    avgFlightPrice: 89,
    rating: 4.8,
    reviews: 45230,
    tags: ['Romantico', 'Arte', 'Gastronomia', 'Historia'],
    images: ['/destinations/paris-1.jpg', '/destinations/paris-2.jpg'],
  },
  {
    id: 'roma',
    name: 'Roma',
    country: 'Italia',
    continent: 'Europa',
    description: 'La Ciudad Eterna, donde la historia antigua se mezcla con la vida moderna. Imprescindible para amantes de la historia y la comida italiana.',
    highlights: ['Coliseo', 'Vaticano', 'Fontana di Trevi', 'Piazza Navona', 'Panteon', 'Foro Romano'],
    bestTime: 'Abril - Junio, Septiembre - Octubre',
    avgTemp: '15°C',
    currency: 'EUR',
    language: 'Italiano',
    timezone: 'UTC+1',
    flightTime: '2h 15m desde Madrid',
    avgFlightPrice: 75,
    rating: 4.7,
    reviews: 38900,
    tags: ['Historia', 'Arte', 'Gastronomia', 'Arquitectura'],
    images: ['/destinations/roma-1.jpg', '/destinations/roma-2.jpg'],
  },
  {
    id: 'tokio',
    name: 'Tokio',
    country: 'Japon',
    continent: 'Asia',
    description: 'Una metropolis donde la tradicion milenaria convive con la tecnologia mas avanzada. Templos antiguos junto a rascacielos futuristas.',
    highlights: ['Templo Senso-ji', 'Shibuya', 'Monte Fuji', 'Akihabara', 'Palacio Imperial', 'Harajuku'],
    bestTime: 'Marzo - Mayo, Octubre - Noviembre',
    avgTemp: '16°C',
    currency: 'JPY',
    language: 'Japones',
    timezone: 'UTC+9',
    flightTime: '14h desde Madrid',
    avgFlightPrice: 650,
    rating: 4.9,
    reviews: 28700,
    tags: ['Cultura', 'Tecnologia', 'Gastronomia', 'Tradicion'],
    images: ['/destinations/tokio-1.jpg', '/destinations/tokio-2.jpg'],
  },
  {
    id: 'nueva-york',
    name: 'Nueva York',
    country: 'Estados Unidos',
    continent: 'America',
    description: 'La Gran Manzana, ciudad que nunca duerme. Iconos culturales, Broadway, arte mundial y la energia unica de Manhattan.',
    highlights: ['Times Square', 'Central Park', 'Estatua de la Libertad', 'Empire State', 'Brooklyn Bridge', 'MoMA'],
    bestTime: 'Abril - Junio, Septiembre - Noviembre',
    avgTemp: '13°C',
    currency: 'USD',
    language: 'Ingles',
    timezone: 'UTC-5',
    flightTime: '8h desde Madrid',
    avgFlightPrice: 420,
    rating: 4.8,
    reviews: 52100,
    tags: ['Urbano', 'Arte', 'Compras', 'Entretenimiento'],
    images: ['/destinations/nyc-1.jpg', '/destinations/nyc-2.jpg'],
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Espana',
    continent: 'Europa',
    description: 'Ciudad mediterranea con arquitectura unica de Gaudi, playas urbanas, gastronomia excepcional y vida nocturna vibrante.',
    highlights: ['Sagrada Familia', 'Park Guell', 'La Rambla', 'Barrio Gotico', 'Casa Batllo', 'La Barceloneta'],
    bestTime: 'Mayo - Junio, Septiembre - Octubre',
    avgTemp: '18°C',
    currency: 'EUR',
    language: 'Espanol, Catalan',
    timezone: 'UTC+1',
    flightTime: '1h 15m desde Madrid',
    avgFlightPrice: 55,
    rating: 4.7,
    reviews: 41200,
    tags: ['Playa', 'Arquitectura', 'Gastronomia', 'Vida nocturna'],
    images: ['/destinations/barcelona-1.jpg', '/destinations/barcelona-2.jpg'],
  },
  {
    id: 'londres',
    name: 'Londres',
    country: 'Reino Unido',
    continent: 'Europa',
    description: 'Capital britanica con siglos de historia, museos de clase mundial gratuitos, teatros legendarios y una escena gastronomica diversa.',
    highlights: ['Big Ben', 'Tower Bridge', 'British Museum', 'Palacio de Buckingham', 'Hyde Park', 'West End'],
    bestTime: 'Mayo - Septiembre',
    avgTemp: '11°C',
    currency: 'GBP',
    language: 'Ingles',
    timezone: 'UTC+0',
    flightTime: '2h 30m desde Madrid',
    avgFlightPrice: 95,
    rating: 4.6,
    reviews: 39800,
    tags: ['Historia', 'Cultura', 'Museos', 'Teatro'],
    images: ['/destinations/london-1.jpg', '/destinations/london-2.jpg'],
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'Emiratos Arabes',
    continent: 'Asia',
    description: 'Ciudad del futuro en el desierto. Rascacielos record, centros comerciales gigantes, playas de lujo y experiencias unicas.',
    highlights: ['Burj Khalifa', 'Palm Jumeirah', 'Dubai Mall', 'Desert Safari', 'Burj Al Arab', 'Dubai Marina'],
    bestTime: 'Noviembre - Marzo',
    avgTemp: '27°C',
    currency: 'AED',
    language: 'Arabe, Ingles',
    timezone: 'UTC+4',
    flightTime: '7h desde Madrid',
    avgFlightPrice: 380,
    rating: 4.7,
    reviews: 31500,
    tags: ['Lujo', 'Compras', 'Moderno', 'Playa'],
    images: ['/destinations/dubai-1.jpg', '/destinations/dubai-2.jpg'],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    description: 'Isla de los dioses. Templos misteriosos, arrozales esmeralda, playas paradisiacas y una espiritualidad unica.',
    highlights: ['Templo Tanah Lot', 'Ubud', 'Arrozales de Tegallalang', 'Seminyak', 'Monte Batur', 'Uluwatu'],
    bestTime: 'Abril - Octubre',
    avgTemp: '28°C',
    currency: 'IDR',
    language: 'Indonesio',
    timezone: 'UTC+8',
    flightTime: '16h desde Madrid',
    avgFlightPrice: 750,
    rating: 4.8,
    reviews: 27300,
    tags: ['Playa', 'Espiritual', 'Naturaleza', 'Bienestar'],
    images: ['/destinations/bali-1.jpg', '/destinations/bali-2.jpg'],
  },
  {
    id: 'cancun',
    name: 'Cancun',
    country: 'Mexico',
    continent: 'America',
    description: 'Paraiso del Caribe mexicano. Playas de arena blanca, aguas turquesas, ruinas mayas cercanas y resorts todo incluido.',
    highlights: ['Zona Hotelera', 'Chichen Itza', 'Isla Mujeres', 'Xcaret', 'Cenotes', 'Playa del Carmen'],
    bestTime: 'Diciembre - Abril',
    avgTemp: '27°C',
    currency: 'MXN',
    language: 'Espanol',
    timezone: 'UTC-5',
    flightTime: '11h desde Madrid',
    avgFlightPrice: 580,
    rating: 4.6,
    reviews: 35600,
    tags: ['Playa', 'Todo incluido', 'Historia Maya', 'Aventura'],
    images: ['/destinations/cancun-1.jpg', '/destinations/cancun-2.jpg'],
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    continent: 'Oceania',
    description: 'Ciudad portuaria vibrante con la iconica Opera House, playas surferas y una calidad de vida envidiable.',
    highlights: ['Opera House', 'Harbour Bridge', 'Bondi Beach', 'The Rocks', 'Blue Mountains', 'Manly'],
    bestTime: 'Septiembre - Noviembre, Marzo - Mayo',
    avgTemp: '18°C',
    currency: 'AUD',
    language: 'Ingles',
    timezone: 'UTC+11',
    flightTime: '22h desde Madrid',
    avgFlightPrice: 980,
    rating: 4.8,
    reviews: 24100,
    tags: ['Playa', 'Urbano', 'Naturaleza', 'Surf'],
    images: ['/destinations/sydney-1.jpg', '/destinations/sydney-2.jpg'],
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Marruecos',
    continent: 'Africa',
    description: 'Ciudad imperial llena de magia. Zocos labrinticos, palacios exoticos, jardines secretos y una explosion de colores y aromas.',
    highlights: ['Medina', 'Plaza Jemaa el-Fna', 'Jardin Majorelle', 'Palacio Bahia', 'Zocos', 'Desierto de Agafay'],
    bestTime: 'Marzo - Mayo, Septiembre - Noviembre',
    avgTemp: '20°C',
    currency: 'MAD',
    language: 'Arabe, Frances',
    timezone: 'UTC+1',
    flightTime: '1h 45m desde Madrid',
    avgFlightPrice: 65,
    rating: 4.5,
    reviews: 29800,
    tags: ['Cultura', 'Exotico', 'Gastronomia', 'Compras'],
    images: ['/destinations/marrakech-1.jpg', '/destinations/marrakech-2.jpg'],
  },
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Grecia',
    continent: 'Europa',
    description: 'Isla volcanica con los atardeceres mas famosos del mundo. Casas blancas con cupulas azules sobre acantilados espectaculares.',
    highlights: ['Oia', 'Fira', 'Playa Roja', 'Akrotiri', 'Volcán', 'Atardecer en Oia'],
    bestTime: 'Abril - Octubre',
    avgTemp: '20°C',
    currency: 'EUR',
    language: 'Griego',
    timezone: 'UTC+2',
    flightTime: '4h desde Madrid',
    avgFlightPrice: 150,
    rating: 4.9,
    reviews: 22500,
    tags: ['Romantico', 'Playa', 'Atardeceres', 'Fotogenico'],
    images: ['/destinations/santorini-1.jpg', '/destinations/santorini-2.jpg'],
  },
]

export const continents = ['Todos', 'Europa', 'Asia', 'America', 'Africa', 'Oceania']
export const tags = ['Todos', 'Playa', 'Historia', 'Gastronomia', 'Romantico', 'Aventura', 'Cultura', 'Urbano', 'Naturaleza', 'Lujo']
